### ISSUE TITLE
Version of Jane Street Core

### ISSUE THREAD

**Issue by jnfoster** [frenetic-lang/frenetic#436] opened 2015-08-27 17:01 UTC
Why are we pinned to 112.24.0? Would it be difficult to update?

-N

**Comment by craig-riecke** [comment] 2015-08-27 17:05
See Issue #425.  There was a proposed solution in issue #431, but it kind of sputtered out without a resolution.

**Comment by craig-riecke** [comment] 2015-09-04 12:08
Duplicate of #431.

**Closed by craig-riecke** 2015-09-04 12:08 UTC
