### ISSUE TITLE
Broken static policy with learning

### ISSUE THREAD

**Issue by mcanini** [frenetic-lang/frenetic#277] opened 2014-04-04 14:45 UTC
@seliopou 
This example (examples/diamond.kat) no longer works with v.2.0.0

```
(* This policy works for

  sudo mn  --controller=remote --topo=tree,2,2 --mac

  pingall should succeed
*)

filter ethTyp=0x806;
  (filter switch=1; filter port=1; (port:=2 | port:=3) |
   filter switch=1; filter not (port=1); port := 1 |
   filter switch=3; filter port=1; (port:=2 | port:=3) |
   filter switch=3; filter not (port=1); port := 1) |
(* Forward when hosts are directly connected. *)
filter (switch=1 and ethDst=1); port := 1 |
filter (switch=3 and ethDst=2); port := 1  |
filter (switch=2 or switch=4); (filter port=1; port:=2 | filter port=2; port:= 1) |
filter switch=1; filter (not ethDst=1); port := 2 |
filter switch=3; filter (not ethDst=2); port := 3
```

here is a more complete static policy which fixes the static fwd issues and works with learning disabled
but when running with learning enabled the example doesn't work (pingall fails)
```
(* This policy works for

  sudo mn  --controller=remote --topo=tree,2,2 --mac

  pingall should succeed
*)

filter ethTyp=0x806;
  (filter switch=2; filter port=1; (port:=2 | port:=3) |
   filter switch=2; filter port=2; (port:=1 | port:=3) |
   filter switch=2; filter port=3; (port:=1 | port:=2) |
   filter switch=3; filter port=1; (port:=2 | port:=3) |
   filter switch=3; filter port=2; (port:=1 | port:=3) |
   filter switch=3; filter port=3; (port:=1 | port:=2)) |
(* Forward when hosts are directly connected. *)
filter ethTyp=0x800;
  (filter (switch=2 and ethDst=1); port := 1 |
   filter (switch=2 and ethDst=2); port := 2 |
   filter (switch=3 and ethDst=3); port := 1 |
   filter (switch=3 and ethDst=4); port := 2 |
   filter switch=2; filter (not ethDst=1 and not ethDst=2); port := 3 |
   filter switch=3; filter (not ethDst=3 and not ethDst=4); port := 3) |
filter switch=1; (filter port=1; port:=2 | filter port=2; port:= 1)
```

**Comment by craig-riecke** [comment] 2016-05-02 20:26
It turns out this has nothing to do with the policy, which is correct.  The problem is the Mininet custom net, which mistakenly creates two interfaces on each host:

```
mininet> h2 ifconfig
h2-eth0   Link encap:Ethernet  HWaddr 00:00:00:00:00:02
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:79 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:6830 (6.8 KB)  TX bytes:196 (196.0 B)

h2-eth0.1 Link encap:Ethernet  HWaddr 00:00:00:00:00:02
          inet addr:10.0.0.2  Bcast:10.255.255.255  Mask:255.0.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:196 (196.0 B)
```

The incoming packets come in on h2-eth0, which has no IP address, and therefore dies.  I will fix the custom net diamond.py and that should fix the issue.

**Comment by craig-riecke** [comment] 2016-05-03 13:07
Fixed in https://github.com/frenetic-lang/frenetic/commit/16a9cb7bcf4011a53abdd7e2397fbe3f01d5d5e0

**Closed by craig-riecke** 2016-05-03 13:07 UTC
